FROM python:3.11 

WORKDIR /app

COPY requirements.txt .
 
EXPOSE 8010

RUN pip install -r requirements.txt

COPY  . .

ENTRYPOINT [ "uvicorn" ]

CMD [ "main:app", "--host", "0.0.0.0", "--port", "8010", "--reload"]
